# Generated by Django 5.0.2 on 2024-05-16 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_source_usersource'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersource',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
